---
title       : playtiems
subtitle    : 
author      : SexxyVeckt0r
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [quiz]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

```{r}


# install.packages( "devtools" )
# require(devtools)
# install_github( "slidify", "ramnathv" )
# install_github( "slidifyLibraries", "ramnathv" )
# require(slidify)
# require(slidifyLibraries)
# 
# setwd("/Volumes/Old_HD/DocStore/=WORK=/=Courses/Software_Carpentry/")
# 
# author( "slidify_example" )


```


## Read-And-Delete

1. Edit YAML front matter
2. Write using R Markdown
3. Use an empty line followed by three dashes to separate slides!

--- .class #id 

## Slide 2

**Markdown** syntax within each slide...

  + bullet
  + list
  + etc..

--- &checkbox

1. wrong
2. taco
3. _correct_


--- Python_too

```{r, engine='python'}

print "this is in python even!?"

```

--- even the shell

```{r, engine='bash'}

pwd

echo shell!

```

